spring.application.name=aurastay
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/aurastay
spring.datasource.username=aura
spring.datasource.password=tigertiger12$$

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-test-query=select 1

# jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# mybatis \uC5D0\uC11C \uD0C0\uC785 \uC815\uC758 \uAE38\uC774\uAC00 \uB108\uBB34 \uAE38\uB2E4. \uCD95\uC57D
mybatis.type-aliases-package=kr.co.aura.aurastay.*

# mapper \uD30C\uC77C\uC758 \uC704\uCE58
# resources \uACBD\uB85C mybatis \uB2E4\uB809\uD1A0\uB9AC \uD558\uC704\uC5D0 \uBAA8\uB4E0 \uB514\uB809\uD1A0\uB9AC\uC5D0\uC11C \uD655\uC7A5\uC790\uAC00 xml \uC778 \uBAA8\uB4E0 \uD30C\uC77C\uC740 \uC804\uBD80
# mapper file \uC784
mybatis.mapper-locations=config/mapper/*.xml

# \uC790\uBC14\uC5D0\uC11C\uB294 \uBCC0\uC218\uBA85\uC744 camel case \uB85C \uD45C\uD604, DB \uC5D0\uC11C\uB294 snake case \uB97C \uC0AC\uC6A9\uD558\uB294\uB370 \uC774 \uB450 \uAC00\uC9C0 \uC2A4\uD0C0\uC77C\uB54C\uBB38\uC5D0 \uC624\uB958\uAC00 \uB098\uC11C \uCD94\uAC00\uD55C \uD56D\uBAA9
# \uC774\uAC78 \uCD94\uAC00\uD558\uBA74 MyBatis \uB294 \uC790\uB3D9\uC73C\uB85C snake case \uCEEC\uB7FC\uBA85\uC744 camel case \uD544\uB4DC\uBA85\uC73C\uB85C \uC790\uB3D9 \uB9E4\uD551\uD574\uC90C
mybatis.configuration.map-underscore-to-camel-case=true
